spring.application.name=CadastroPersonagens

## DataBaseInfo
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:~/testdb
spring.datasource.username=sa
spring.datasource.password=

#H2DB
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console